### ISSUE TITLE
Invalid LESS output in 0.9.4

### ISSUE THREAD

**Issue by boye** [jorgebastida/glue#146]
This morning I have upgraded to `0.9.4` and I just ran into a weird issue. Perhaps I have overlooked an option...but it seems there is something wrong when using LESS as ouput in combination with retina.

Perhaps can @jorgebastida (or someone else) provide me a good example on how to get proper LESS output together with retina sprites? :)

My sprite.conf looks as follows:

```
[sprite]
css_cachebuster=true
img_dir=assets/images/sprites/
margin=5
css_namespace=spr
less_dir=assets/css/sprites/
less_template=assets/images/sprites/template.jinja
ratios=2,1
```

and the command that I'm using:

```
glue assets/images/sprites/src/ --img=assets/images/sprites/ --less=assets/css/sprites/ --project
```

my .jinja file (taken from the documentation example):

```
/* glue: {{ version }} hash: {{ hash }} */
{% for image in images %}.{{ image.label }}{{ image.pseudo }}{%- if not image.last %}, {%- endif %}{%- endfor %}{
    background-image: url('{{ sprite_path }}');
    background-repeat: no-repeat;
    display: inline-block;
    *display: inline;
    *zoom: 1;
}
{% for image in images %}
.{{ image.label }}{{ image.pseudo }}{
    background-position:{{ image.x ~ ('px' if image.x) }} {{ image.y ~ ('px' if image.y) }};
    width:{{ image.width }}px;
    height:{{ image.height }}px;
}
{% endfor %}
{% for ratio in ratios %}
@media screen and (-webkit-min-device-pixel-ratio: {{ ratio.ratio }}), screen and (min--moz-device-pixel-ratio: {{ ratio.ratio }}),screen and (-o-min-device-piratio: {{ ratio.fraction }}),screen and (min-device-pixel-ratio: {{ ratio.ratio }}){
    {% for image in images %}.{{ image.label }}{{ image.pseudo }}{% if not image.last %}, {% endif %}
    {% endfor %}{
        background-image: url('{{ ratio.sprite_path }}');
        -webkit-background-size: {{ width }}px {{ height }}px;
        -moz-background-size: {{ width }}px {{ height }}px;
        background-size: {{ width }}px {{ height }}px;
    }
}
{% endfor %}
```

my output:

``` css
/* glue: 0.9.4 hash: a72ac693c5 */
.spr-main-logo-x,.spr-main-logo-y{
    background-image: url('../../images/sprites/main.png?a72ac693c5');
    background-repeat: no-repeat;
    display: inline-block;
    *display: inline;
    *zoom: 1;
}

.spr-main-logo-x{
    background-position:-5px -5px;
    width:268px;
    height:30px;
}

.spr-main-logo-y{
    background-position:-5px -45px;
    width:254px;
    height:39px;
}


@media screen and (-webkit-min-device-pixel-ratio: ), screen and (min--moz-device-pixel-ratio: ),screen and (-o-min-device-piratio: ),screen and (min-device-pixel-ratio: ){
    .spr-main-logo-x, 
    .spr-main-logo-y
    {
        background-image: url('');
        -webkit-background-size: 413px 398px;
        -moz-background-size: 413px 398px;
        background-size: 413px 398px;
    }
}

@media screen and (-webkit-min-device-pixel-ratio: ), screen and (min--moz-device-pixel-ratio: ),screen and (-o-min-device-piratio: ),screen and (min-device-pixel-ratio: ){
    .spr-main-logo-x, 
    .spr-main-logo-y
    {
        background-image: url('');
        -webkit-background-size: 413px 398px;
        -moz-background-size: 413px 398px;
        background-size: 413px 398px;
    }
}
```
